// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApiClient.Models
{
    /// <summary> The Product. </summary>
    public partial class Product
    {
        /// <summary> Initializes a new instance of <see cref="Product"/>. </summary>
        internal Product()
        {
        }

        /// <summary> Initializes a new instance of <see cref="Product"/>. </summary>
        /// <param name="sku"></param>
        /// <param name="name"></param>
        internal Product(string sku, string name)
        {
            Sku = sku;
            Name = name;
        }

        /// <summary> Gets the sku. </summary>
        public string Sku { get; }
        /// <summary> Gets the name. </summary>
        public string Name { get; }
    }
}
