// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using ApiClient;
using Azure.Core.Extensions;

namespace Microsoft.Extensions.Azure
{
    /// <summary> Extension methods to add <see cref="ProductApiV1Client"/> to client builder. </summary>
    public static partial class ApiClientClientBuilderExtensions
    {
        /// <summary> Registers a <see cref="ProductApiV1Client"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="endpoint"> server parameter. </param>
        public static IAzureClientBuilder<ProductApiV1Client, ProductApiV1ClientOptions> AddProductApiV1Client<TBuilder>(this TBuilder builder, Uri endpoint)
        where TBuilder : IAzureClientFactoryBuilder
        {
            return builder.RegisterClientFactory<ProductApiV1Client, ProductApiV1ClientOptions>((options) => new ProductApiV1Client(endpoint, options));
        }

        /// <summary> Registers a <see cref="ProductApiV1Client"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="configuration"> The configuration values. </param>
        public static IAzureClientBuilder<ProductApiV1Client, ProductApiV1ClientOptions> AddProductApiV1Client<TBuilder, TConfiguration>(this TBuilder builder, TConfiguration configuration)
        where TBuilder : IAzureClientFactoryBuilderWithConfiguration<TConfiguration>
        {
            return builder.RegisterClientFactory<ProductApiV1Client, ProductApiV1ClientOptions>(configuration);
        }
    }
}
