// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace ApiClient.Models
{
    /// <summary> Model factory for models. </summary>
    public static partial class ApiClientModelFactory
    {
        /// <summary> Initializes a new instance of <see cref="Models.Product"/>. </summary>
        /// <param name="sku"></param>
        /// <param name="name"></param>
        /// <returns> A new <see cref="Models.Product"/> instance for mocking. </returns>
        public static Product Product(string sku = null, string name = null)
        {
            return new Product(sku, name);
        }
    }
}
