// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using ApiClient.Models;
using Azure;
using Azure.Core.Pipeline;

namespace ApiClient
{
    /// <summary> The Product service client. </summary>
    public partial class ProductClient
    {
        private readonly ClientDiagnostics _clientDiagnostics;
        private readonly HttpPipeline _pipeline;
        internal ProductRestClient RestClient { get; }

        /// <summary> Initializes a new instance of ProductClient for mocking. </summary>
        protected ProductClient()
        {
        }

        /// <summary> Initializes a new instance of ProductClient. </summary>
        /// <param name="clientDiagnostics"> The handler for diagnostic messaging in the client. </param>
        /// <param name="pipeline"> The HTTP pipeline for sending and receiving REST requests and responses. </param>
        /// <param name="endpoint"> server parameter. </param>
        /// <exception cref="ArgumentNullException"> <paramref name="clientDiagnostics"/> or <paramref name="pipeline"/> is null. </exception>
        internal ProductClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri endpoint = null)
        {
            RestClient = new ProductRestClient(clientDiagnostics, pipeline, endpoint);
            _clientDiagnostics = clientDiagnostics;
            _pipeline = pipeline;
        }

        /// <summary> Retrieves a list of sample products. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Generates and returns five sample products with SKU and name for demo purposes. </remarks>
        public virtual async Task<Response<IReadOnlyList<Product>>> GetProductsAsync(CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ProductClient.GetProducts");
            scope.Start();
            try
            {
                return await RestClient.GetProductsAsync(cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }

        /// <summary> Retrieves a list of sample products. </summary>
        /// <param name="cancellationToken"> The cancellation token to use. </param>
        /// <remarks> Generates and returns five sample products with SKU and name for demo purposes. </remarks>
        public virtual Response<IReadOnlyList<Product>> GetProducts(CancellationToken cancellationToken = default)
        {
            using var scope = _clientDiagnostics.CreateScope("ProductClient.GetProducts");
            scope.Start();
            try
            {
                return RestClient.GetProducts(cancellationToken);
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
    }
}
